theme: jekyll-theme-minimal
logo: https://avatars.githubusercontent.com/u/60957608
title: Berkeley-Data
description: Berkeley Data represents an evolving body of work to support data science teams curated by current and former students of the Berkeley MIDS program
